name: Python file utils

on:
  push:
    branches: [ main ]
    paths-ignore: [ '*.rst', '*.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '*.rst', '*.md' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@main
    - name: Set up ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint file_utils
    - name: Test with pytest
      run: |
        pytest
    - name: "Generate code coverage"
      run: |
        coverage run --source=file_utils -m pytest
        coverage report -m
        coverage xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        verbose: true 
        token: ${{ secrets.CODECOV_TOKEN }}